#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 28 15:38:41 2019

This calculates the number of subpolynomials of a given boolean polynomial. 
Polynomials are encoded as a collection of subsets of a ground set [n].

@author: lnajt
"""

import random
import copy
import numpy as np
def random_poly(n = 10, m = 3, d = 5):

    ground_set = set(range(n))
    terms = set([])
    
    for k in range(m):
        pre_term = random.sample(ground_set,d)
        pre_term.sort()
        term = frozenset(pre_term)
        terms.add(term)
    
    polynomial = frozenset(terms)
    return(polynomial)
    
    
    
def mod2(term_list):
    #takes a list of terms, and returns the set of terms that appear
    #an odd number of times.
    
    terms = set(term_list)
    odd_terms = set([])
    for q in terms:
        if len([x for x in term_list if x == q]) % 2 == 1:
            odd_terms.add(q)
            
    return odd_terms

def compute_subpoly(polynomial, n):
    subpolys = set([])
    subpolys.add(polynomial)
    list_of_subs = [ set( [polynomial])]
    for i in range(n):
        new_polys = set([])
        
        #i set to 0 phase:
        for q in list_of_subs[i]:
            new_q = set([])
            for t in q:
                if i not in t:
                    new_q.add(t)
            new_q = frozenset(new_q)
            new_polys.add(new_q)
        
        #i set to 1 phase:
        for q in list_of_subs[i]:
            new_q = []
            for t in q:
                if i not in t:
                    new_q.append(t)
                if i in t:
                    t_new = set(copy.deepcopy(t))
                    t_new.remove(i)
                    t_new = frozenset(t_new)
                    new_q.add(t_new)
                    
            new_q = mod2(new_q)        
            new_q = frozenset(new_q)
            new_polys.add(new_q)
        #print("step:" + str(new_polys) + "\n")
        #subpolys = subpolys.union(new_polys)
        list_of_subs.append(new_polys)
        
    subpoly = subpolys.union(*list_of_subs)
    print(subpoly)
    #print(len(subpoly))
    
    return len(subpoly)

def test():
    n = 3
    values = list(range(n))
    poly = frozenset([frozenset( values)])
    compute_subpoly(poly, n)
    
    ##Ooops, this will handle $x_0x_1 + x_1x_2$ incorrectly, because it doesn't
    #comput $1 + 1$ correctly.
    
def experiment():
    n = 50
    for m in range(3,40,2):
        d = 10
        list_of_counts = []
        for k in range(2):
            poly = random_poly(n,m,d)
            list_of_counts.append((compute_subpoly(poly, n)))
        print("at m: " +  str(m) + " counts: ", np.mean(list_of_counts))
